import type { Metadata, Viewport } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import KonstaProvider from "./konsta-provider";
import { cookies } from "next/headers";
import { AuthProvider } from "./context/auth-context";
import { getParseUser } from "./lib/parse-server";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 1, // prevents auto-zoom
  themeColor: "#ffffff",
};

export const metadata: Metadata = {
  title: "To-Do App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const sessionToken: string | undefined =
    cookieStore.get("session_token")?.value;
  let user = sessionToken ? await getParseUser(sessionToken) : null;
  console.log(`User is ${user}`);

  const authData = { sessionToken, user: user };
  return (
    <html lang="en">
      <body>
        <AuthProvider value={authData}>
          <KonstaProvider>{children}</KonstaProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
